export enum EventType {
    ORDER_SHIPPED = 'ORDER_SHIPPED',
    SPECIMEN_RECEIVED = 'SPECIMEN_RECEIVED',
    SPECIMEN_REJECTED = 'SPECIMEN_REJECTED',
    SPECIMEN_ACCEPTED = 'SPECIMEN_ACCEPTED',
    SPECIMEN_PROCESS_INPROGRESS = 'SPECIMEN_PROCESS_INPROGRESS',
    SPECIMEN_PROCESS_COMPLETE = 'SPECIMEN_PROCESS_COMPLETE',
    REPORT_READY = 'REPORT_READY',
    PERSON_CONSULT_REQUEST_SENT = 'PERSON_CONSULT_REQUEST_SENT',
    PERSON_CONSULT_BOOKED = 'PERSON_CONSULT_BOOKED',
    PERSON_CONSULT_COMPLETED = 'PERSON_CONSULT_COMPLETED',
    PRESCRIPTION_SENT_TO_PHARMACY = 'PRESCRIPTION_SENT_TO_PHARMACY',
  }